### ISSUE TITLE
Errors from scoreboard.py at the end of a run

### ISSUE THREAD

**Issue by chengzhuzhang** [rubisco-sfa/ILAMB#43]
Hi there, 

An error from scoreboard.py occurs when @acordonez and I ran ilamb though cmec-driver with latest master. 

When i try to use ilamb-run to run ilamb standalone, I got the same error as below:
 

Traceback (most recent call last):
  File "/home/zhang40/miniconda3/envs/ilamb/bin/ilamb-run", line 682, in <module>
    S.createHtml(M)
  File "/home/zhang40/miniconda3/envs/ilamb/lib/python3.7/site-packages/ILAMB/Scoreboard.py", line 420, in createHtml
    scores,rel_tree = self.createJSON(M)
  File "/home/zhang40/miniconda3/envs/ilamb/lib/python3.7/site-packages/ILAMB/Scoreboard.py", line 393, in createJSON
    rel_tree = GenerateRelationshipTree(self,M)
  File "/home/zhang40/miniconda3/envs/ilamb/lib/python3.7/site-packages/ILAMB/Scoreboard.py", line 958, in GenerateRelationshipTree
    h2 = Node(data.confrontation.longname)
AttributeError: 'NoneType' object has no attribute 'longname'

Any suggestions or insights are welcome. Thank you!

**Comment by nocollier** [comment]
Thanks for the report, here is what is going on:

* ILAMB uses configure files to build a tree of comparisons to run, this is
how we can generate hierarchical mean scores
* As we go, when we find the 'relationship' keyword, we look at variable to
variable comparisons
* These relationships go into their own summary section at the end of
overview figure

So in your error stack, I see that we were building the relationship tree
and effectively one of the nodes of that tree is unexpectedly set to None.
In the past we have dealt with two issues that produce similar errors:

* Your configure file has no relationships specified (which is fine, we
just weren't careful originally)
* Your configure file specifies a relationship to a variable that isn't
present in the configure file.

For example, in the past you might see this if you had specified a
relationship of GPP with TAS but TAS wasn't in your configure file. This is
a temporary limitation because ILAMB harvests mean information out of the
temporary files.

But both of these bugs have been fixed, I cannot produce your error
locally.

I know cmec-driver runs things for you, but can you locate the configure
file and what git hash of ILAMB you are running?

**Comment by chengzhuzhang** [comment]
Hi @nocollier Thank you so much for the clarification. Ana also helped trouble shooting, and it looks like the both DATA and ILAMB_sample data on our server is outdated. After updating the dataset, I get a nice view of scoreboard with the testing data!
