### ISSUE TITLE
add the changelog or released.md?

### ISSUE THREAD

**Issue by minxu74** [rubisco-sfa/ILAMB#9]
It seems that there is no document in the repository to describe the incremental changes among the versions.  These documents are helpful for users to track the differences in results from the different versions of ILAMB.

**Comment by nocollier** [comment]
I am not a fan of these. I already give release notes about the major changes between releases. If you really wanted to know you could look at past versions of README.md, but even this might not tell you the whole story. 

Score changes could occur for reasons not relating to this codebase. The observational data might have been updated, or you could have run ilamb in a different way. A while back we switched to running ilamb with a redefinition of the "global" region to be global land. This is because our, say, pr scores were measuring all of the globe and muddling our understanding of what was happening on just land. This caused some shifts in the scores but has nothing to do with this codebase. 

But I agree we need someway to communicate these things to users. Given our limited developer resources, I would rather improve on the test suite I have to make it something we could continuously integrate, and then update the tests to reflect how we are actually running ilamb. Then you could look up the history for the gold scores:

https://github.com/rubisco-sfa/ILAMB/commits/master/test/scores_test.csv.gold

and it would have relevant information about what causes shifts.

**Comment by nocollier** [comment]
See #10

**Comment by nocollier** [comment]
After discussion with @minxu74 we wonder if in addition to the improved testing, if we should have a place to write short technical/science descriptions for changes to the methodology. For example, we are currently changing the nbp methodology to include a score for the trajectory of accumulated carbon, which deviates from the ILAMB paper description. The flavor of these writeups would be an addendum of sorts to the methodology that explains what was changed and why.

I think that this is a very good idea, but the question remains of where to host them. They are perhaps too short/limited for actual publication. I feel that the important aspects of these are that they are (1) publicly available and easy to find and (2) citable.

**Comment by nocollier** [comment]
Another example: we need some small writeup of what the CO2 emulation does.

**Comment by nocollier** [comment]
I made an initial [draft](https://www.ilamb.org/Addenda/2020_03_nbp.pdf) of the nbp methodology changes, anticipating that this will be important information as we write papers. For now, I made a directory `www.ilamb.org/Addenda` where we can host these short pieces. This makes them publicly available, but not citable. Any ideas on how we might do better? Do you think this is a good way to go? @minxu74 @climate-dude

**Comment by minxu74** [comment]
@nocollier @climate-dude Great, there is a document to describe major science changes on ILAMB. For citation, does the figshare work? It can host not only data, figures, but also documents. It is easy to publish them and get DOIs for citation, meanwhile  it can track any revisions on the documents that are already published.

**Comment by nocollier** [comment]
Good idea @minxu74, what do you think of [this](https://doi.org/10.6084/m9.figshare.12020808.v1)?

https://doi.org/10.6084/m9.figshare.12020808.v1

@climate-dude ?
